<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConferenceHallBooking.Domain\ConferenceHallBooking.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviours\" />
    <Folder Include="Configuration\" />
    <Folder Include="DTOs\" />
    <Folder Include="Extensions\" />
    <Folder Include="Features\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappers\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
